{"name": "test_add_new_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'", "trace": "self = <allure_commons._allure.fixture object at 0x0000026FF7377C10>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\nvenv\\lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nrequest = <SubRequest 'take_screenshot_on_failure' for <Function test_add_new_user>>\n\n    @pytest.fixture(autouse=True)\n    def take_screenshot_on_failure(request):\n        \"\"\"Automatically take a screenshot if a test fails and print the screenshot path.\"\"\"\n        yield  # Run the test first\n>       if request.node.rep_call.failed:  # Check if the test failed\nE       AttributeError: 'Function' object has no attribute 'rep_call'\n\nconftest.py:34: AttributeError"}, "description": "Test adding a new user functionality.", "start": 1728981333074, "stop": 1728981343672, "uuid": "7cb826fc-dd53-4575-a63c-54bc6f287644", "historyId": "e96d2a558c394c3566b8aa6cb56d8e17", "testCaseId": "e96d2a558c394c3566b8aa6cb56d8e17", "fullName": "tests.test_orangehrm.TestOrangeHRM#test_add_new_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_orangehrm"}, {"name": "subSuite", "value": "TestOrangeHRM"}, {"name": "host", "value": "LAPTOP-2G5H132K"}, {"name": "thread", "value": "17920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_orangehrm"}]}